version: 2
updates:
    - package-ecosystem: npm
      directory: "/"
      schedule:
          interval: daily
          time: "10:00"
      open-pull-requests-limit: 10
      ignore:
          - dependency-name: "@testing-library/user-event"
            versions:
                - 12.7.2
                - 12.8.0
                - 12.8.1
                - 12.8.3
                - 13.0.0
                - 13.0.1
                - 13.0.10
                - 13.0.14
                - 13.0.2
                - 13.0.7
                - 13.0.8
                - 13.1.0
                - 13.1.1
                - 13.1.2
                - 13.1.3
                - 13.1.5
          - dependency-name: react-markdown
            versions:
                - 6.0.0
          - dependency-name: emoji-picker-react
            versions:
                - 3.4.3
                - 3.4.4
          - dependency-name: "@apollo/client"
            versions:
                - 3.3.12
          - dependency-name: notistack
            versions:
                - 1.0.5
          - dependency-name: react
            versions:
                - 17.0.2
